---

- name: Find the boot UUIDs
  block:
    - name: Find var uuid
      shell: blkid -o value -s UUID {{ vol_drive }}5
      register: uuid_var
    
    - name: Find log uuid
      shell: blkid -o value -s UUID {{ vol_drive }}6
      register: uuid_log

    - name: Find opt uuid
      shell: blkid -o value -s UUID {{ vol_drive }}7
      register: uuid_vartmp
    
    - name: Find audit uuid
      shell: blkid -o value -s UUID {{ vol_drive }}8
      register: uuid_audit
    
    - name: Find home uuid
      shell: blkid -o value -s UUID {{ vol_drive }}9
      register: uuid_home
    
    - name: Find tmp uuid
      shell: blkid -o value -s UUID {{ vol_drive }}10
      register: uuid_tmp

- name: Update the /etc/fstab
  block:
    - name: Update fstab for var
      mount:
        path: /var
        src: UUID={{ uuid_var.stdout_lines[0] }}
        fstype: "xfs"
        opts: nodev
        state: present

    - name: Update fstab for log
      mount:
        path: /var/log
        src: UUID={{ uuid_log.stdout_lines[0] }}
        fstype: "xfs"
        opts: nodev,nosuid,noexec
        state: present

    - name: Update fstab for opt
      mount:
        path: /opt
        src: UUID={{ uuid_vartmp.stdout_lines[0] }}
        fstype: "xfs"
        opts: nodev,nosuid,noexec
        state: present

    - name: Update fstab for audit
      mount:
        path: /var/log/audit
        src: UUID={{ uuid_audit.stdout_lines[0] }}
        fstype: "xfs"
        opts: nodev,nosuid,noexec
        state: present
    
    - name: Update fstab for home
      mount:
        path: /home
        src: UUID={{ uuid_home.stdout_lines[0] }}
        fstype: "xfs"
        opts: nodev
        state: present

    - name: Update fstab for tmp
      mount:
        path: /tmp
        src: UUID={{ uuid_tmp.stdout_lines[0] }}
        fstype: "xfs"
        opts: nodev,nosuid,noexec
        state: present
